name: "Build and Deploy"

on:
  push:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: "Fetch Dependencies"
        run: npm install
      - name: "Run Build, Minify, and Publish"
        run: npm run publish
      - uses: actions/upload-artifact@v3.1.1
        with:
          name: site-files
          path: ./dist/
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    environment: aws-production
    steps:
      - uses: actions/download-artifact@v3.0.1
        with:
          name: site-files
          path: ./dist
      - name: "Setup AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
      - name: "Run Sync"
        run: aws s3 sync ./dist s3://${{ secrets.BUCKET_NAME }}
      - name: "Invalidate CloudFront Distribution"
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
